[2024-11-14T02:18:10.857+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-14T02:18:10.914+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AlphaVantageTimeSeriesDaily_AAPL_MSFT.extract scheduled__2024-11-13T00:00:00+00:00 [queued]>
[2024-11-14T02:18:10.930+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AlphaVantageTimeSeriesDaily_AAPL_MSFT.extract scheduled__2024-11-13T00:00:00+00:00 [queued]>
[2024-11-14T02:18:10.931+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-14T02:18:10.960+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2024-11-13 00:00:00+00:00
[2024-11-14T02:18:10.972+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AlphaVantageTimeSeriesDaily_AAPL_MSFT', 'extract', 'scheduled__2024-11-13T00:00:00+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/ETLstockprice.py', '--cfg-path', '/tmp/tmpjz4j9r5u']
[2024-11-14T02:18:10.977+0000] {standard_task_runner.py:91} INFO - Job 129: Subtask extract
[2024-11-14T02:18:10.983+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=258) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-14T02:18:10.985+0000] {standard_task_runner.py:63} INFO - Started process 280 to run task
[2024-11-14T02:18:11.069+0000] {task_command.py:426} INFO - Running <TaskInstance: AlphaVantageTimeSeriesDaily_AAPL_MSFT.extract scheduled__2024-11-13T00:00:00+00:00 [running]> on host b955513b8419
[2024-11-14T02:18:11.233+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AlphaVantageTimeSeriesDaily_AAPL_MSFT' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-11-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-13T00:00:00+00:00'
[2024-11-14T02:18:11.235+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-14T02:18:11.252+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-14T02:18:11.253+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ETLstockprice.py", line 20, in extract
    api_key = Variable.get("ALPHA_VANTAGE_API_KEY")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable ALPHA_VANTAGE_API_KEY does not exist'
[2024-11-14T02:18:11.296+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=AlphaVantageTimeSeriesDaily_AAPL_MSFT, task_id=extract, run_id=scheduled__2024-11-13T00:00:00+00:00, execution_date=20241113T000000, start_date=20241114T021810, end_date=20241114T021811
[2024-11-14T02:18:11.326+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 129 for task extract ('Variable ALPHA_VANTAGE_API_KEY does not exist'; 280)
[2024-11-14T02:18:11.361+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-14T02:18:11.377+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
