[2024-11-14T02:20:13.845+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-14T02:20:13.904+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AlphaVantageTimeSeriesDaily_AAPL_MSFT.extract manual__2024-11-14T02:20:11.396239+00:00 [queued]>
[2024-11-14T02:20:13.914+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AlphaVantageTimeSeriesDaily_AAPL_MSFT.extract manual__2024-11-14T02:20:11.396239+00:00 [queued]>
[2024-11-14T02:20:13.915+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-14T02:20:13.931+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2024-11-14 02:20:11.396239+00:00
[2024-11-14T02:20:13.940+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AlphaVantageTimeSeriesDaily_AAPL_MSFT', 'extract', 'manual__2024-11-14T02:20:11.396239+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/ETLstockprice.py', '--cfg-path', '/tmp/tmpnm4m8gap']
[2024-11-14T02:20:13.942+0000] {standard_task_runner.py:91} INFO - Job 130: Subtask extract
[2024-11-14T02:20:13.943+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=350) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-14T02:20:13.944+0000] {standard_task_runner.py:63} INFO - Started process 377 to run task
[2024-11-14T02:20:13.996+0000] {task_command.py:426} INFO - Running <TaskInstance: AlphaVantageTimeSeriesDaily_AAPL_MSFT.extract manual__2024-11-14T02:20:11.396239+00:00 [running]> on host b955513b8419
[2024-11-14T02:20:14.096+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AlphaVantageTimeSeriesDaily_AAPL_MSFT' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T02:20:11.396239+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T02:20:11.396239+00:00'
[2024-11-14T02:20:14.097+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-14T02:20:14.105+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-14T02:20:14.107+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ETLstockprice.py", line 20, in extract
    api_key = Variable.get("ALPHA_VANTAGE_API_KEY")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable ALPHA_VANTAGE_API_KEY does not exist'
[2024-11-14T02:20:14.120+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=AlphaVantageTimeSeriesDaily_AAPL_MSFT, task_id=extract, run_id=manual__2024-11-14T02:20:11.396239+00:00, execution_date=20241114T022011, start_date=20241114T022013, end_date=20241114T022014
[2024-11-14T02:20:14.133+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 130 for task extract ('Variable ALPHA_VANTAGE_API_KEY does not exist'; 377)
[2024-11-14T02:20:14.158+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-14T02:20:14.182+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-14T02:20:14.190+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
