[2024-11-14T02:20:13.855+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-14T02:20:13.907+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AlphaVantageTimeSeriesDaily_AAPL_MSFT.extract__1 manual__2024-11-14T02:20:11.396239+00:00 [queued]>
[2024-11-14T02:20:13.916+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AlphaVantageTimeSeriesDaily_AAPL_MSFT.extract__1 manual__2024-11-14T02:20:11.396239+00:00 [queued]>
[2024-11-14T02:20:13.918+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-14T02:20:13.939+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract__1> on 2024-11-14 02:20:11.396239+00:00
[2024-11-14T02:20:13.947+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AlphaVantageTimeSeriesDaily_AAPL_MSFT', 'extract__1', 'manual__2024-11-14T02:20:11.396239+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/ETLstockprice.py', '--cfg-path', '/tmp/tmp_48ilhjc']
[2024-11-14T02:20:13.950+0000] {standard_task_runner.py:91} INFO - Job 131: Subtask extract__1
[2024-11-14T02:20:13.951+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=351) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-14T02:20:13.952+0000] {standard_task_runner.py:63} INFO - Started process 378 to run task
[2024-11-14T02:20:14.007+0000] {task_command.py:426} INFO - Running <TaskInstance: AlphaVantageTimeSeriesDaily_AAPL_MSFT.extract__1 manual__2024-11-14T02:20:11.396239+00:00 [running]> on host b955513b8419
[2024-11-14T02:20:14.102+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AlphaVantageTimeSeriesDaily_AAPL_MSFT' AIRFLOW_CTX_TASK_ID='extract__1' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T02:20:11.396239+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T02:20:11.396239+00:00'
[2024-11-14T02:20:14.103+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-14T02:20:14.110+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-14T02:20:14.111+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ETLstockprice.py", line 20, in extract
    api_key = Variable.get("ALPHA_VANTAGE_API_KEY")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable ALPHA_VANTAGE_API_KEY does not exist'
[2024-11-14T02:20:14.122+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=AlphaVantageTimeSeriesDaily_AAPL_MSFT, task_id=extract__1, run_id=manual__2024-11-14T02:20:11.396239+00:00, execution_date=20241114T022011, start_date=20241114T022013, end_date=20241114T022014
[2024-11-14T02:20:14.140+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 131 for task extract__1 ('Variable ALPHA_VANTAGE_API_KEY does not exist'; 378)
[2024-11-14T02:20:14.167+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-14T02:20:14.177+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
